# Servidor
server.port=8080

# Configuración del esquema y conexión a Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/controlMedico_DB?currentSchema=control_medico
spring.datasource.username=postgres
spring.datasource.password=12345
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hibernate
spring.jpa.properties.hibernate.default_schema=control_medico
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Credenciales fijas para el Login
spring.security.user.name=admin
spring.security.user.password=12345